openapi: 3.0.0
info:
  title: Adoptions API
  version: 1.0.0
paths:
  /api/adoptions:
    get:
      summary: Obtiene todas las adopciones
      tags: [Adoptions]
      responses:
        '200':
          description: Lista de adopciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Adoption'
        '500':
          description: Error interno del servidor
  /api/adoptions/{aid}:
    get:
      summary: Obtiene una adopción por ID
      tags: [Adoptions]
      parameters:
        - in: path
          name: aid
          required: true
          schema:
            type: string
          description: ID de la adopción
      responses:
        '200':
          description: Adopción encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adoption'
        '404':
          description: Adopción no encontrada
        '500':
          description: Error interno del servidor
  /api/adoptions/{uid}/{pid}:
    post:
      summary: Crea una nueva adopción
      tags: [Adoptions]
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
          description: ID del usuario
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID de la mascota
      responses:
        '201':
          description: Adopción creada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adoption'
        '400':
          description: Datos de entrada inválidos
        '500':
          description: Error interno del servidor
components:
  schemas:
    Adoption:
      type: object
      properties:
        _id:
          type: string
          description: ID de la adopción
        userId:
          type: string
          description: ID del usuario adoptante
        petId:
          type: string
          description: ID de la mascota adoptada
        adoptionDate:
          type: string
          format: date-time
          description: Fecha de adopción